"""added_main_models

Revision ID: 4a21cf5bbfd2
Revises: f9a6a518d6cd
Create Date: 2024-11-09 16:03:21.254027

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a21cf5bbfd2"
down_revision: Union[str, None] = "f9a6a518d6cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("video_path", sa.String(), nullable=True),
        sa.Column("transcription", sa.String(), nullable=True),
        sa.Column("resume_path", sa.String(), nullable=True),
        sa.Column("motivation_letter", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "personality_model",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("parameter", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("card", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card"],
            ["card.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("user", sa.Column("is_admin", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_admin")
    op.drop_table("personality_model")
    op.drop_table("card")
    # ### end Alembic commands ###
