"""add_vacancy

Revision ID: 64f4f4d80984
Revises: 4a21cf5bbfd2
Create Date: 2024-11-09 22:18:33.321651

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64f4f4d80984"
down_revision: Union[str, None] = "4a21cf5bbfd2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vacancy",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("salary", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("personality_model", sa.Column("vacancy", sa.Uuid(), nullable=True))
    op.alter_column("personality_model", "card", existing_type=sa.UUID(), nullable=True)
    op.create_foreign_key(None, "personality_model", "vacancy", ["vacancy"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "personality_model", type_="foreignkey")
    op.alter_column(
        "personality_model", "card", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("personality_model", "vacancy")
    op.drop_table("vacancy")
    # ### end Alembic commands ###
